### PR TITLE
Update docker machine to v1.10.3

### PR DESCRIPTION
**Pull request by mikesplain**

### CODE REVIEW

**Comment by chrisbaron** [comment]
i'd like to see this run on someone else's machine, like @jaypatel11 or @andrewpopeo to see if it's smooth for anyone else fist.

**Comment by mikesplain** [comment]
I don't disagree, it won't affect anything till the next time someone creates their docker-machine

**Comment by mikesplain** [comment]
@jaypatel11 or @andrewpopeo mind giving my branch a try?

**Comment by andrewpopeo** [comment]
Ran cleanly on my end. Anything other than boxen that I can run to make sure the update hasn't broken anything?

**Comment by andrewpopeo** [comment]
+1

**Comment by mikesplain** [comment]
Thanks gang

**Comment by chrisbaron** [comment]
+1

**Pull request merged**
