### PR TITLE
DEV-396 -- updated puppetfile to use puppet-virtualbox

### PR DESCRIPTION
**Pull request by sccsas**
Updates virtualbox to latest stable release 4.3.26

### CODE REVIEW

**Comment by sccsas** [comment]
@mikesplain please review for +1

**Comment by sccsas** [comment]
Notice: class cylent::apps::default_apps declared
Notice: /Stage[main]/Cylent::Apps::Default_apps/Notify[class cylent::apps::default_apps declared]/message: defined 'message' as 'class cylent::apps::default_apps declared'
Notice: Repository Defaults Set
Notice: /Stage[main]/Cylent::Dev_environment/Notify[Repository Defaults Set]/message: defined 'message' as 'Repository Defaults Set'
Notice: /Stage[main]/Virtualbox/Package[VirtualBox-4.3.26-98988]/ensure: created
Notice: /Stage[main]/Projects::Etcd/Exec[foreman]/returns: executed successfully
Notice: /Stage[main]/Projects::Etcd/Exec[unzip etcd]/returns: executed successfully
Notice: /Stage[main]/Postgresql::Service/Exec[init-postgresql-db]/returns: executed successfully
Notice: /Stage[main]/Postgresql::Service/Exec[kill-stale-postgres-pidfile]/returns: executed successfully
Notice: /Stage[main]/Postgresql::Service/Exec[wait-for-postgresql]/returns: executed successfully

**Comment by mikesplain** [comment]
Worked for me too.  You need to shutdown your running virtualboxes so:

```
boot2docker stop
```

And if you get an error, sometimes loose VirtualBox Processes are still running:

```
ps aux | grep Virtual | awk '{print $2}' |xargs kill -9
```

**Comment by mikesplain** [comment]
But yeah +1

**Pull request merged**
